[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"
evm_version = "paris"
via_ir = false
optimizer = true
optimizer_runs = 200
solc_version = "0.8.23"
remappings = []

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

